package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * AdminAudit generated by hbm2java
 */
@Entity
@Table(name="AdminAudit", schema="dbo"
)
public class AdminAudit  implements java.io.Serializable {


     private Long auditId;
     private long staffId;
     private String actionType;
     private String targetType;
     private long targetId;
     private String reason;
     private String details;
     private OffsetDateTime occurredAt;

    public AdminAudit() {
    }

	
    public AdminAudit(long staffId, String actionType, String targetType, long targetId, OffsetDateTime occurredAt) {
        this.staffId = staffId;
        this.actionType = actionType;
        this.targetType = targetType;
        this.targetId = targetId;
        this.occurredAt = occurredAt;
    }
    public AdminAudit(long staffId, String actionType, String targetType, long targetId, String reason, String details, OffsetDateTime occurredAt) {
       this.staffId = staffId;
       this.actionType = actionType;
       this.targetType = targetType;
       this.targetId = targetId;
       this.reason = reason;
       this.details = details;
       this.occurredAt = occurredAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AuditId", nullable=false, columnDefinition="bigint")
    public Long getAuditId() {
        return this.auditId;
    }
    
    public void setAuditId(Long auditId) {
        this.auditId = auditId;
    }

    
    @Column(name="StaffId", nullable=false, columnDefinition="bigint")
    public long getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(long staffId) {
        this.staffId = staffId;
    }

    
    @Column(name="ActionType", nullable=false, length=80, columnDefinition="varchar(80)")
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    
    @Column(name="TargetType", nullable=false, length=80, columnDefinition="varchar(80)")
    public String getTargetType() {
        return this.targetType;
    }
    
    public void setTargetType(String targetType) {
        this.targetType = targetType;
    }

    
    @Column(name="TargetId", nullable=false, columnDefinition="bigint")
    public long getTargetId() {
        return this.targetId;
    }
    
    public void setTargetId(long targetId) {
        this.targetId = targetId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", length=2000, columnDefinition="nvarchar(2000)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Details", length=2147483647, columnDefinition="nvarchar(max)")
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="OccurredAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }
    
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }




}


