package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * ArtistAppeal generated by hbm2java
 */
@Entity
@Table(name="ArtistAppeal", schema="dbo"
)
public class ArtistAppeal  implements java.io.Serializable {


     private Long appealId;
     private long suspensionId;
     private long artistId;
     private String body;
     private String status;
     private Long decidedByStaffId;
     private String decisionReason;
     private OffsetDateTime createdAt;
     private OffsetDateTime decidedAt;

    public ArtistAppeal() {
    }

	
    public ArtistAppeal(long suspensionId, long artistId, String body, String status, OffsetDateTime createdAt) {
        this.suspensionId = suspensionId;
        this.artistId = artistId;
        this.body = body;
        this.status = status;
        this.createdAt = createdAt;
    }
    public ArtistAppeal(long suspensionId, long artistId, String body, String status, Long decidedByStaffId, String decisionReason, OffsetDateTime createdAt, OffsetDateTime decidedAt) {
       this.suspensionId = suspensionId;
       this.artistId = artistId;
       this.body = body;
       this.status = status;
       this.decidedByStaffId = decidedByStaffId;
       this.decisionReason = decisionReason;
       this.createdAt = createdAt;
       this.decidedAt = decidedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AppealId", nullable=false, columnDefinition="bigint")
    public Long getAppealId() {
        return this.appealId;
    }
    
    public void setAppealId(Long appealId) {
        this.appealId = appealId;
    }

    
    @Column(name="SuspensionId", nullable=false, columnDefinition="bigint")
    public long getSuspensionId() {
        return this.suspensionId;
    }
    
    public void setSuspensionId(long suspensionId) {
        this.suspensionId = suspensionId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Body", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="DecidedByStaffId", columnDefinition="bigint")
    public Long getDecidedByStaffId() {
        return this.decidedByStaffId;
    }
    
    public void setDecidedByStaffId(Long decidedByStaffId) {
        this.decidedByStaffId = decidedByStaffId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="DecisionReason", length=2000, columnDefinition="nvarchar(2000)")
    public String getDecisionReason() {
        return this.decisionReason;
    }
    
    public void setDecisionReason(String decisionReason) {
        this.decisionReason = decisionReason;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="DecidedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getDecidedAt() {
        return this.decidedAt;
    }
    
    public void setDecidedAt(OffsetDateTime decidedAt) {
        this.decidedAt = decidedAt;
    }




}


