package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * ArtistSuspension generated by hbm2java
 */
@Entity
@Table(name="ArtistSuspension", schema="dbo"
    
)
public class ArtistSuspension  implements java.io.Serializable {


     private Long suspensionId;
     private long artistId;
     private OffsetDateTime startedAt;
     private OffsetDateTime endsAt;
     private OffsetDateTime closedAt;
     private String reason;
     private long staffId;

    public ArtistSuspension() {
    }

	
    public ArtistSuspension(long artistId, OffsetDateTime startedAt, String reason, long staffId) {
        this.artistId = artistId;
        this.startedAt = startedAt;
        this.reason = reason;
        this.staffId = staffId;
    }
    public ArtistSuspension(long artistId, OffsetDateTime startedAt, OffsetDateTime endsAt, OffsetDateTime closedAt, String reason, long staffId) {
       this.artistId = artistId;
       this.startedAt = startedAt;
       this.endsAt = endsAt;
       this.closedAt = closedAt;
       this.reason = reason;
       this.staffId = staffId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="SuspensionId", nullable=false, columnDefinition="bigint")
    public Long getSuspensionId() {
        return this.suspensionId;
    }
    
    public void setSuspensionId(Long suspensionId) {
        this.suspensionId = suspensionId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="StartedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getStartedAt() {
        return this.startedAt;
    }
    
    public void setStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="EndsAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getEndsAt() {
        return this.endsAt;
    }
    
    public void setEndsAt(OffsetDateTime endsAt) {
        this.endsAt = endsAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ClosedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getClosedAt() {
        return this.closedAt;
    }
    
    public void setClosedAt(OffsetDateTime closedAt) {
        this.closedAt = closedAt;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", nullable=false, length=2000, columnDefinition="nvarchar(2000)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="StaffId", nullable=false, columnDefinition="bigint")
    public long getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(long staffId) {
        this.staffId = staffId;
    }




}


