package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * ArtistProceeds generated by hbm2java
 */
@Entity
@Table(name="ArtistProceeds", schema="dbo"
    
)
public class ArtistProceeds  implements java.io.Serializable {


     private Long proceedsId;
     private long artistId;
     private Long orderItemId;
     private Long quoteId;
     private BigDecimal amount;
     private String currencyCode;
     private String status;
     private OffsetDateTime eligibleAt;
     private OffsetDateTime paidAt;

    public ArtistProceeds() {
    }

	
    public ArtistProceeds(long artistId, BigDecimal amount, String currencyCode, String status) {
        this.artistId = artistId;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.status = status;
    }
    public ArtistProceeds(long artistId, Long orderItemId, Long quoteId, BigDecimal amount, String currencyCode, String status, OffsetDateTime eligibleAt, OffsetDateTime paidAt) {
       this.artistId = artistId;
       this.orderItemId = orderItemId;
       this.quoteId = quoteId;
       this.amount = amount;
       this.currencyCode = currencyCode;
       this.status = status;
       this.eligibleAt = eligibleAt;
       this.paidAt = paidAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ProceedsId", nullable=false, columnDefinition="bigint")
    public Long getProceedsId() {
        return this.proceedsId;
    }
    
    public void setProceedsId(Long proceedsId) {
        this.proceedsId = proceedsId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @Column(name="OrderItemId", columnDefinition="bigint")
    public Long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="QuoteId", columnDefinition="bigint")
    public Long getQuoteId() {
        return this.quoteId;
    }
    
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="EligibleAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getEligibleAt() {
        return this.eligibleAt;
    }
    
    public void setEligibleAt(OffsetDateTime eligibleAt) {
        this.eligibleAt = eligibleAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PaidAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPaidAt() {
        return this.paidAt;
    }
    
    public void setPaidAt(OffsetDateTime paidAt) {
        this.paidAt = paidAt;
    }




}


