package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * ArtistProfile generated by hbm2java
 */
@Entity
@Table(name="ArtistProfile", schema="dbo"
    
)
public class ArtistProfile  implements java.io.Serializable {


     private Long artistId;
     private long userId;
     private String displayName;
     private String bio;
     private String status;
     private boolean acceptingCommissions;
     private BigDecimal startingPrice;
     private long authorizedByStaffId;
     private OffsetDateTime createdAt;
     private byte[] rowVer;

    public ArtistProfile() {
    }

	
    public ArtistProfile(long userId, String displayName, String status, boolean acceptingCommissions, long authorizedByStaffId, OffsetDateTime createdAt, byte[] rowVer) {
        this.userId = userId;
        this.displayName = displayName;
        this.status = status;
        this.acceptingCommissions = acceptingCommissions;
        this.authorizedByStaffId = authorizedByStaffId;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public ArtistProfile(long userId, String displayName, String bio, String status, boolean acceptingCommissions, BigDecimal startingPrice, long authorizedByStaffId, OffsetDateTime createdAt, byte[] rowVer) {
       this.userId = userId;
       this.displayName = displayName;
       this.bio = bio;
       this.status = status;
       this.acceptingCommissions = acceptingCommissions;
       this.startingPrice = startingPrice;
       this.authorizedByStaffId = authorizedByStaffId;
       this.createdAt = createdAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public Long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(Long artistId) {
        this.artistId = artistId;
    }

    
    @Column(name="UserId", nullable=false, columnDefinition="bigint")
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="DisplayName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Bio", length=2147483647, columnDefinition="nvarchar(max)")
    public String getBio() {
        return this.bio;
    }
    
    public void setBio(String bio) {
        this.bio = bio;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="AcceptingCommissions", nullable=false, columnDefinition="bit")
    public boolean isAcceptingCommissions() {
        return this.acceptingCommissions;
    }
    
    public void setAcceptingCommissions(boolean acceptingCommissions) {
        this.acceptingCommissions = acceptingCommissions;
    }

    
    @Column(name="StartingPrice", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getStartingPrice() {
        return this.startingPrice;
    }
    
    public void setStartingPrice(BigDecimal startingPrice) {
        this.startingPrice = startingPrice;
    }

    
    @Column(name="AuthorizedByStaffId", nullable=false, columnDefinition="bigint")
    public long getAuthorizedByStaffId() {
        return this.authorizedByStaffId;
    }
    
    public void setAuthorizedByStaffId(long authorizedByStaffId) {
        this.authorizedByStaffId = authorizedByStaffId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


