package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * ArtworkMedia generated by hbm2java
 */
@Entity
@Table(name="ArtworkMedia", schema="dbo"
    
)
public class ArtworkMedia  implements java.io.Serializable {


     private Long artworkMediaId;
     private long artworkId;
     private long fileId;
     private int sortOrder;

    public ArtworkMedia() {
    }

    public ArtworkMedia(long artworkId, long fileId, int sortOrder) {
       this.artworkId = artworkId;
       this.fileId = fileId;
       this.sortOrder = sortOrder;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ArtworkMediaId", nullable=false, columnDefinition="bigint")
    public Long getArtworkMediaId() {
        return this.artworkMediaId;
    }
    
    public void setArtworkMediaId(Long artworkMediaId) {
        this.artworkMediaId = artworkMediaId;
    }

    
    @Column(name="ArtworkId", nullable=false, columnDefinition="bigint")
    public long getArtworkId() {
        return this.artworkId;
    }
    
    public void setArtworkId(long artworkId) {
        this.artworkId = artworkId;
    }

    
    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }

    
    @Column(name="SortOrder", nullable=false, columnDefinition="int")
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }




}


