package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * Artwork generated by hbm2java
 */
@Entity
@Table(name="Artwork", schema="dbo"
    
)
public class Artwork  implements java.io.Serializable {


     private Long artworkId;
     private long artistId;
     private String title;
     private String description;
     private String dimension;
     private String status;
     private OffsetDateTime publishedAt;
     private OffsetDateTime createdAt;
     private byte[] rowVer;

    public Artwork() {
    }

	
    public Artwork(long artistId, String title, String dimension, String status, OffsetDateTime createdAt, byte[] rowVer) {
        this.artistId = artistId;
        this.title = title;
        this.dimension = dimension;
        this.status = status;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public Artwork(long artistId, String title, String description, String dimension, String status, OffsetDateTime publishedAt, OffsetDateTime createdAt, byte[] rowVer) {
       this.artistId = artistId;
       this.title = title;
       this.description = description;
       this.dimension = dimension;
       this.status = status;
       this.publishedAt = publishedAt;
       this.createdAt = createdAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ArtworkId", nullable=false, columnDefinition="bigint")
    public Long getArtworkId() {
        return this.artworkId;
    }
    
    public void setArtworkId(Long artworkId) {
        this.artworkId = artworkId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Title", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Description", length=2147483647, columnDefinition="nvarchar(max)")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Dimension", nullable=false, length=2, columnDefinition="char(2)")
    public String getDimension() {
        return this.dimension;
    }
    
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PublishedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPublishedAt() {
        return this.publishedAt;
    }
    
    public void setPublishedAt(OffsetDateTime publishedAt) {
        this.publishedAt = publishedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


