package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * ArtworkTag generated by hbm2java
 */
@Entity
@Table(name="ArtworkTag", schema="dbo"
)
public class ArtworkTag  implements java.io.Serializable {


     private ArtworkTagId id;

    public ArtworkTag() {
    }

    public ArtworkTag(ArtworkTagId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="artworkId", column=@Column(name="ArtworkId", nullable=false, columnDefinition="bigint") ), 
        @AttributeOverride(name="tagId", column=@Column(name="TagId", nullable=false, columnDefinition="int") ) } )
    public ArtworkTagId getId() {
        return this.id;
    }
    
    public void setId(ArtworkTagId id) {
        this.id = id;
    }




}


