package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * ArtworkTagId generated by hbm2java
 */
@Embeddable
public class ArtworkTagId  implements java.io.Serializable {


     private long artworkId;
     private int tagId;

    public ArtworkTagId() {
    }

    public ArtworkTagId(long artworkId, int tagId) {
       this.artworkId = artworkId;
       this.tagId = tagId;
    }
   


    @Column(name="ArtworkId", nullable=false, columnDefinition="bigint")
    public long getArtworkId() {
        return this.artworkId;
    }
    
    public void setArtworkId(long artworkId) {
        this.artworkId = artworkId;
    }


    @Column(name="TagId", nullable=false, columnDefinition="int")
    public int getTagId() {
        return this.tagId;
    }
    
    public void setTagId(int tagId) {
        this.tagId = tagId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArtworkTagId) ) return false;
		 ArtworkTagId castOther = ( ArtworkTagId ) other; 
         
		 return (this.getArtworkId()==castOther.getArtworkId())
 && (this.getTagId()==castOther.getTagId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + (int) this.getArtworkId();
        result = 37 * result + this.getTagId();
         return result;
   }   


}


