package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CancellationRequest generated by hbm2java
 */
@Entity
@Table(name="CancellationRequest", schema="dbo"
    
)
public class CancellationRequest  implements java.io.Serializable {


     private Long cancellationId;
     private long commissionId;
     private long requestedByUserId;
     private String reason;
     private String status;
     private OffsetDateTime createdAt;
     private OffsetDateTime resolvedAt;

    public CancellationRequest() {
    }

	
    public CancellationRequest(long commissionId, long requestedByUserId, String reason, String status, OffsetDateTime createdAt) {
        this.commissionId = commissionId;
        this.requestedByUserId = requestedByUserId;
        this.reason = reason;
        this.status = status;
        this.createdAt = createdAt;
    }
    public CancellationRequest(long commissionId, long requestedByUserId, String reason, String status, OffsetDateTime createdAt, OffsetDateTime resolvedAt) {
       this.commissionId = commissionId;
       this.requestedByUserId = requestedByUserId;
       this.reason = reason;
       this.status = status;
       this.createdAt = createdAt;
       this.resolvedAt = resolvedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CancellationId", nullable=false, columnDefinition="bigint")
    public Long getCancellationId() {
        return this.cancellationId;
    }
    
    public void setCancellationId(Long cancellationId) {
        this.cancellationId = cancellationId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="RequestedByUserId", nullable=false, columnDefinition="bigint")
    public long getRequestedByUserId() {
        return this.requestedByUserId;
    }
    
    public void setRequestedByUserId(long requestedByUserId) {
        this.requestedByUserId = requestedByUserId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ResolvedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getResolvedAt() {
        return this.resolvedAt;
    }
    
    public void setResolvedAt(OffsetDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }




}


