package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * CartItem generated by hbm2java
 */
@Entity
@Table(name="CartItem", schema="dbo"
)
public class CartItem  implements java.io.Serializable {


     private CartItemId id;
     private int quantity;

    public CartItem() {
    }

    public CartItem(CartItemId id, int quantity) {
       this.id = id;
       this.quantity = quantity;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="cartId", column=@Column(name="CartId", nullable=false, columnDefinition="bigint") ), 
        @AttributeOverride(name="listingId", column=@Column(name="ListingId", nullable=false, columnDefinition="bigint") ) } )
    public CartItemId getId() {
        return this.id;
    }
    
    public void setId(CartItemId id) {
        this.id = id;
    }

    
    @Column(name="Quantity", nullable=false, columnDefinition="int")
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


