package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name="Cart", schema="dbo"
    
)
public class Cart  implements java.io.Serializable {


     private Long cartId;
     private long userId;
     private OffsetDateTime updatedAt;
     private byte[] rowVer;

    public Cart() {
    }

    public Cart(long userId, OffsetDateTime updatedAt, byte[] rowVer) {
       this.userId = userId;
       this.updatedAt = updatedAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CartId", nullable=false, columnDefinition="bigint")
    public Long getCartId() {
        return this.cartId;
    }
    
    public void setCartId(Long cartId) {
        this.cartId = cartId;
    }

    
    @Column(name="UserId", nullable=false, columnDefinition="bigint")
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="UpdatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


