package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CartItemId generated by hbm2java
 */
@Embeddable
public class CartItemId  implements java.io.Serializable {


     private long cartId;
     private long listingId;

    public CartItemId() {
    }

    public CartItemId(long cartId, long listingId) {
       this.cartId = cartId;
       this.listingId = listingId;
    }
   


    @Column(name="CartId", nullable=false, columnDefinition="bigint")
    public long getCartId() {
        return this.cartId;
    }
    
    public void setCartId(long cartId) {
        this.cartId = cartId;
    }


    @Column(name="ListingId", nullable=false, columnDefinition="bigint")
    public long getListingId() {
        return this.listingId;
    }
    
    public void setListingId(long listingId) {
        this.listingId = listingId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartItemId) ) return false;
		 CartItemId castOther = ( CartItemId ) other; 
         
		 return (this.getCartId()==castOther.getCartId())
 && (this.getListingId()==castOther.getListingId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + (int) this.getCartId();
        result = 37 * result + (int) this.getListingId();
         return result;
   }   


}


