package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CommissionMessage generated by hbm2java
 */
@Entity
@Table(name="CommissionMessage", schema="dbo"
)
public class CommissionMessage  implements java.io.Serializable {


     private Long messageId;
     private long commissionId;
     private long senderUserId;
     private String body;
     private OffsetDateTime sentAt;

    public CommissionMessage() {
    }

    public CommissionMessage(long commissionId, long senderUserId, String body, OffsetDateTime sentAt) {
       this.commissionId = commissionId;
       this.senderUserId = senderUserId;
       this.body = body;
       this.sentAt = sentAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="MessageId", nullable=false, columnDefinition="bigint")
    public Long getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Long messageId) {
        this.messageId = messageId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="SenderUserId", nullable=false, columnDefinition="bigint")
    public long getSenderUserId() {
        return this.senderUserId;
    }
    
    public void setSenderUserId(long senderUserId) {
        this.senderUserId = senderUserId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Body", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getBody() {
        return this.body;
    }
    
    public void setBody(String body) {
        this.body = body;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="SentAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getSentAt() {
        return this.sentAt;
    }
    
    public void setSentAt(OffsetDateTime sentAt) {
        this.sentAt = sentAt;
    }




}


