package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CommissionDeliverable generated by hbm2java
 */
@Entity
@Table(name="CommissionDeliverable", schema="dbo"
    
)
public class CommissionDeliverable  implements java.io.Serializable {


     private Long deliverableId;
     private long commissionId;
     private int versionNo;
     private String notes;
     private OffsetDateTime submittedAt;

    public CommissionDeliverable() {
    }

	
    public CommissionDeliverable(long commissionId, int versionNo, OffsetDateTime submittedAt) {
        this.commissionId = commissionId;
        this.versionNo = versionNo;
        this.submittedAt = submittedAt;
    }
    public CommissionDeliverable(long commissionId, int versionNo, String notes, OffsetDateTime submittedAt) {
       this.commissionId = commissionId;
       this.versionNo = versionNo;
       this.notes = notes;
       this.submittedAt = submittedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DeliverableId", nullable=false, columnDefinition="bigint")
    public Long getDeliverableId() {
        return this.deliverableId;
    }
    
    public void setDeliverableId(Long deliverableId) {
        this.deliverableId = deliverableId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="VersionNo", nullable=false, columnDefinition="int")
    public int getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(int versionNo) {
        this.versionNo = versionNo;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Notes", length=2147483647, columnDefinition="nvarchar(max)")
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="SubmittedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getSubmittedAt() {
        return this.submittedAt;
    }
    
    public void setSubmittedAt(OffsetDateTime submittedAt) {
        this.submittedAt = submittedAt;
    }




}


