package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * CommissionQuote generated by hbm2java
 */
@Entity
@Table(name="CommissionQuote", schema="dbo"
    
)
public class CommissionQuote  implements java.io.Serializable {


     private Long quoteId;
     private long commissionId;
     private int sequenceNo;
     private String scopeText;
     private String expectedCompletionTerms;
     private BigDecimal price;
     private BigDecimal taxAmount;
     private String currencyCode;
     private BigDecimal feeRate;
     private BigDecimal feeAmount;
     private BigDecimal artistProceeds;
     private String status;
     private OffsetDateTime offeredAt;
     private OffsetDateTime acceptedAt;
     private OffsetDateTime paidAt;

    public CommissionQuote() {
    }

	
    public CommissionQuote(long commissionId, int sequenceNo, String scopeText, String expectedCompletionTerms, BigDecimal price, BigDecimal taxAmount, String currencyCode, String status, OffsetDateTime offeredAt) {
        this.commissionId = commissionId;
        this.sequenceNo = sequenceNo;
        this.scopeText = scopeText;
        this.expectedCompletionTerms = expectedCompletionTerms;
        this.price = price;
        this.taxAmount = taxAmount;
        this.currencyCode = currencyCode;
        this.status = status;
        this.offeredAt = offeredAt;
    }
    public CommissionQuote(long commissionId, int sequenceNo, String scopeText, String expectedCompletionTerms, BigDecimal price, BigDecimal taxAmount, String currencyCode, BigDecimal feeRate, BigDecimal feeAmount, BigDecimal artistProceeds, String status, OffsetDateTime offeredAt, OffsetDateTime acceptedAt, OffsetDateTime paidAt) {
       this.commissionId = commissionId;
       this.sequenceNo = sequenceNo;
       this.scopeText = scopeText;
       this.expectedCompletionTerms = expectedCompletionTerms;
       this.price = price;
       this.taxAmount = taxAmount;
       this.currencyCode = currencyCode;
       this.feeRate = feeRate;
       this.feeAmount = feeAmount;
       this.artistProceeds = artistProceeds;
       this.status = status;
       this.offeredAt = offeredAt;
       this.acceptedAt = acceptedAt;
       this.paidAt = paidAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="QuoteId", nullable=false, columnDefinition="bigint")
    public Long getQuoteId() {
        return this.quoteId;
    }
    
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="SequenceNo", nullable=false, columnDefinition="int")
    public int getSequenceNo() {
        return this.sequenceNo;
    }
    
    public void setSequenceNo(int sequenceNo) {
        this.sequenceNo = sequenceNo;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ScopeText", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getScopeText() {
        return this.scopeText;
    }
    
    public void setScopeText(String scopeText) {
        this.scopeText = scopeText;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ExpectedCompletionTerms", nullable=false, length=1000, columnDefinition="nvarchar(1000)")
    public String getExpectedCompletionTerms() {
        return this.expectedCompletionTerms;
    }
    
    public void setExpectedCompletionTerms(String expectedCompletionTerms) {
        this.expectedCompletionTerms = expectedCompletionTerms;
    }

    
    @Column(name="Price", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="TaxAmount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="FeeRate", precision=9, scale=6, columnDefinition="decimal(9,6)")
    public BigDecimal getFeeRate() {
        return this.feeRate;
    }
    
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    
    @Column(name="FeeAmount", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }
    
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    
    @Column(name="ArtistProceeds", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getArtistProceeds() {
        return this.artistProceeds;
    }
    
    public void setArtistProceeds(BigDecimal artistProceeds) {
        this.artistProceeds = artistProceeds;
    }

    
    @Column(name="Status", nullable=false, length=18, columnDefinition="varchar(18)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="OfferedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getOfferedAt() {
        return this.offeredAt;
    }
    
    public void setOfferedAt(OffsetDateTime offeredAt) {
        this.offeredAt = offeredAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="AcceptedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getAcceptedAt() {
        return this.acceptedAt;
    }
    
    public void setAcceptedAt(OffsetDateTime acceptedAt) {
        this.acceptedAt = acceptedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PaidAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPaidAt() {
        return this.paidAt;
    }
    
    public void setPaidAt(OffsetDateTime paidAt) {
        this.paidAt = paidAt;
    }




}


