package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CommissionAttachment generated by hbm2java
 */
@Entity
@Table(name="CommissionAttachment", schema="dbo"
)
public class CommissionAttachment  implements java.io.Serializable {


     private Long attachmentId;
     private long commissionId;
     private long fileId;
     private long uploadedByUserId;
     private OffsetDateTime createdAt;

    public CommissionAttachment() {
    }

    public CommissionAttachment(long commissionId, long fileId, long uploadedByUserId, OffsetDateTime createdAt) {
       this.commissionId = commissionId;
       this.fileId = fileId;
       this.uploadedByUserId = uploadedByUserId;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AttachmentId", nullable=false, columnDefinition="bigint")
    public Long getAttachmentId() {
        return this.attachmentId;
    }
    
    public void setAttachmentId(Long attachmentId) {
        this.attachmentId = attachmentId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }

    
    @Column(name="UploadedByUserId", nullable=false, columnDefinition="bigint")
    public long getUploadedByUserId() {
        return this.uploadedByUserId;
    }
    
    public void setUploadedByUserId(long uploadedByUserId) {
        this.uploadedByUserId = uploadedByUserId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


