package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CommissionDispute generated by hbm2java
 */
@Entity
@Table(name="CommissionDispute", schema="dbo"
    
)
public class CommissionDispute  implements java.io.Serializable {


     private Long disputeId;
     private long commissionId;
     private long openedByUserId;
     private String reason;
     private String status;
     private String outcome;
     private Long decidedByStaffId;
     private OffsetDateTime openedAt;
     private OffsetDateTime resolvedAt;

    public CommissionDispute() {
    }

	
    public CommissionDispute(long commissionId, long openedByUserId, String reason, String status, OffsetDateTime openedAt) {
        this.commissionId = commissionId;
        this.openedByUserId = openedByUserId;
        this.reason = reason;
        this.status = status;
        this.openedAt = openedAt;
    }
    public CommissionDispute(long commissionId, long openedByUserId, String reason, String status, String outcome, Long decidedByStaffId, OffsetDateTime openedAt, OffsetDateTime resolvedAt) {
       this.commissionId = commissionId;
       this.openedByUserId = openedByUserId;
       this.reason = reason;
       this.status = status;
       this.outcome = outcome;
       this.decidedByStaffId = decidedByStaffId;
       this.openedAt = openedAt;
       this.resolvedAt = resolvedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="DisputeId", nullable=false, columnDefinition="bigint")
    public Long getDisputeId() {
        return this.disputeId;
    }
    
    public void setDisputeId(Long disputeId) {
        this.disputeId = disputeId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="OpenedByUserId", nullable=false, columnDefinition="bigint")
    public long getOpenedByUserId() {
        return this.openedByUserId;
    }
    
    public void setOpenedByUserId(long openedByUserId) {
        this.openedByUserId = openedByUserId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="Outcome", length=24, columnDefinition="varchar(24)")
    public String getOutcome() {
        return this.outcome;
    }
    
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }

    
    @Column(name="DecidedByStaffId", columnDefinition="bigint")
    public Long getDecidedByStaffId() {
        return this.decidedByStaffId;
    }
    
    public void setDecidedByStaffId(Long decidedByStaffId) {
        this.decidedByStaffId = decidedByStaffId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="OpenedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getOpenedAt() {
        return this.openedAt;
    }
    
    public void setOpenedAt(OffsetDateTime openedAt) {
        this.openedAt = openedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ResolvedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getResolvedAt() {
        return this.resolvedAt;
    }
    
    public void setResolvedAt(OffsetDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }




}


