package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name="Commission", schema="dbo"
)
public class Commission  implements java.io.Serializable {


     private Long commissionId;
     private long customerId;
     private long artistId;
     private String requestDescription;
     private String status;
     private String customerNameSnapshot;
     private String artistNameSnapshot;
     private OffsetDateTime createdAt;
     private OffsetDateTime completedAt;
     private byte[] rowVer;

    public Commission() {
    }

	
    public Commission(long customerId, long artistId, String requestDescription, String status, String artistNameSnapshot, OffsetDateTime createdAt, byte[] rowVer) {
        this.customerId = customerId;
        this.artistId = artistId;
        this.requestDescription = requestDescription;
        this.status = status;
        this.artistNameSnapshot = artistNameSnapshot;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public Commission(long customerId, long artistId, String requestDescription, String status, String customerNameSnapshot, String artistNameSnapshot, OffsetDateTime createdAt, OffsetDateTime completedAt, byte[] rowVer) {
       this.customerId = customerId;
       this.artistId = artistId;
       this.requestDescription = requestDescription;
       this.status = status;
       this.customerNameSnapshot = customerNameSnapshot;
       this.artistNameSnapshot = artistNameSnapshot;
       this.createdAt = createdAt;
       this.completedAt = completedAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public Long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(Long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="CustomerId", nullable=false, columnDefinition="bigint")
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="RequestDescription", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getRequestDescription() {
        return this.requestDescription;
    }
    
    public void setRequestDescription(String requestDescription) {
        this.requestDescription = requestDescription;
    }

    
    @Column(name="Status", nullable=false, length=24, columnDefinition="varchar(24)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="CustomerNameSnapshot", length=160, columnDefinition="nvarchar(160)")
    public String getCustomerNameSnapshot() {
        return this.customerNameSnapshot;
    }
    
    public void setCustomerNameSnapshot(String customerNameSnapshot) {
        this.customerNameSnapshot = customerNameSnapshot;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ArtistNameSnapshot", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getArtistNameSnapshot() {
        return this.artistNameSnapshot;
    }
    
    public void setArtistNameSnapshot(String artistNameSnapshot) {
        this.artistNameSnapshot = artistNameSnapshot;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CompletedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCompletedAt() {
        return this.completedAt;
    }
    
    public void setCompletedAt(OffsetDateTime completedAt) {
        this.completedAt = completedAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


