package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CommissionEvent generated by hbm2java
 */
@Entity
@Table(name="CommissionEvent", schema="dbo"
)
public class CommissionEvent  implements java.io.Serializable {


     private Long eventId;
     private long commissionId;
     private String eventType;
     private String fromStatus;
     private String toStatus;
     private Long relatedId;
     private Long actorUserId;
     private Long actorStaffId;
     private OffsetDateTime occurredAt;
     private String details;

    public CommissionEvent() {
    }

	
    public CommissionEvent(long commissionId, String eventType, OffsetDateTime occurredAt) {
        this.commissionId = commissionId;
        this.eventType = eventType;
        this.occurredAt = occurredAt;
    }
    public CommissionEvent(long commissionId, String eventType, String fromStatus, String toStatus, Long relatedId, Long actorUserId, Long actorStaffId, OffsetDateTime occurredAt, String details) {
       this.commissionId = commissionId;
       this.eventType = eventType;
       this.fromStatus = fromStatus;
       this.toStatus = toStatus;
       this.relatedId = relatedId;
       this.actorUserId = actorUserId;
       this.actorStaffId = actorStaffId;
       this.occurredAt = occurredAt;
       this.details = details;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EventId", nullable=false, columnDefinition="bigint")
    public Long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="EventType", nullable=false, length=40, columnDefinition="varchar(40)")
    public String getEventType() {
        return this.eventType;
    }
    
    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    
    @Column(name="FromStatus", length=24, columnDefinition="varchar(24)")
    public String getFromStatus() {
        return this.fromStatus;
    }
    
    public void setFromStatus(String fromStatus) {
        this.fromStatus = fromStatus;
    }

    
    @Column(name="ToStatus", length=24, columnDefinition="varchar(24)")
    public String getToStatus() {
        return this.toStatus;
    }
    
    public void setToStatus(String toStatus) {
        this.toStatus = toStatus;
    }

    
    @Column(name="RelatedId", columnDefinition="bigint")
    public Long getRelatedId() {
        return this.relatedId;
    }
    
    public void setRelatedId(Long relatedId) {
        this.relatedId = relatedId;
    }

    
    @Column(name="ActorUserId", columnDefinition="bigint")
    public Long getActorUserId() {
        return this.actorUserId;
    }
    
    public void setActorUserId(Long actorUserId) {
        this.actorUserId = actorUserId;
    }

    
    @Column(name="ActorStaffId", columnDefinition="bigint")
    public Long getActorStaffId() {
        return this.actorStaffId;
    }
    
    public void setActorStaffId(Long actorStaffId) {
        this.actorStaffId = actorStaffId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="OccurredAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }
    
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Details", length=2147483647, columnDefinition="nvarchar(max)")
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }




}


