package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * CustomerAddress generated by hbm2java
 */
@Entity
@Table(name="CustomerAddress", schema="dbo"
    
)
public class CustomerAddress  implements java.io.Serializable {


     private Long addressId;
     private long userId;
     private String label;
     private String recipientName;
     private String phone;
     private String line1;
     private String line2;
     private String ward;
     private String district;
     private String provinceCode;
     private String postalCode;
     private String countryCode;
     private boolean isDefault;
     private OffsetDateTime deletedAt;
     private OffsetDateTime createdAt;
     private byte[] rowVer;

    public CustomerAddress() {
    }

	
    public CustomerAddress(long userId, String recipientName, String phone, String line1, String provinceCode, String countryCode, boolean isDefault, OffsetDateTime createdAt, byte[] rowVer) {
        this.userId = userId;
        this.recipientName = recipientName;
        this.phone = phone;
        this.line1 = line1;
        this.provinceCode = provinceCode;
        this.countryCode = countryCode;
        this.isDefault = isDefault;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public CustomerAddress(long userId, String label, String recipientName, String phone, String line1, String line2, String ward, String district, String provinceCode, String postalCode, String countryCode, boolean isDefault, OffsetDateTime deletedAt, OffsetDateTime createdAt, byte[] rowVer) {
       this.userId = userId;
       this.label = label;
       this.recipientName = recipientName;
       this.phone = phone;
       this.line1 = line1;
       this.line2 = line2;
       this.ward = ward;
       this.district = district;
       this.provinceCode = provinceCode;
       this.postalCode = postalCode;
       this.countryCode = countryCode;
       this.isDefault = isDefault;
       this.deletedAt = deletedAt;
       this.createdAt = createdAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AddressId", nullable=false, columnDefinition="bigint")
    public Long getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Long addressId) {
        this.addressId = addressId;
    }

    
    @Column(name="UserId", nullable=false, columnDefinition="bigint")
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Label", length=80, columnDefinition="nvarchar(80)")
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="RecipientName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getRecipientName() {
        return this.recipientName;
    }
    
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Phone", nullable=false, length=40, columnDefinition="nvarchar(40)")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Line1", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getLine1() {
        return this.line1;
    }
    
    public void setLine1(String line1) {
        this.line1 = line1;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Line2", length=240, columnDefinition="nvarchar(240)")
    public String getLine2() {
        return this.line2;
    }
    
    public void setLine2(String line2) {
        this.line2 = line2;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Ward", length=160, columnDefinition="nvarchar(160)")
    public String getWard() {
        return this.ward;
    }
    
    public void setWard(String ward) {
        this.ward = ward;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="District", length=160, columnDefinition="nvarchar(160)")
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="ProvinceCode", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="PostalCode", length=20, columnDefinition="nvarchar(20)")
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="CountryCode", nullable=false, length=2, columnDefinition="char(2)")
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }

    
    @Column(name="IsDefault", nullable=false, columnDefinition="bit")
    public boolean isIsDefault() {
        return this.isDefault;
    }
    
    public void setIsDefault(boolean isDefault) {
        this.isDefault = isDefault;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="DeletedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(OffsetDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


