package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * DeliverableFileId generated by hbm2java
 */
@Embeddable
public class DeliverableFileId  implements java.io.Serializable {


     private long deliverableId;
     private long fileId;

    public DeliverableFileId() {
    }

    public DeliverableFileId(long deliverableId, long fileId) {
       this.deliverableId = deliverableId;
       this.fileId = fileId;
    }
   


    @Column(name="DeliverableId", nullable=false, columnDefinition="bigint")
    public long getDeliverableId() {
        return this.deliverableId;
    }
    
    public void setDeliverableId(long deliverableId) {
        this.deliverableId = deliverableId;
    }


    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeliverableFileId) ) return false;
		 DeliverableFileId castOther = ( DeliverableFileId ) other; 
         
		 return (this.getDeliverableId()==castOther.getDeliverableId())
 && (this.getFileId()==castOther.getFileId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + (int) this.getDeliverableId();
        result = 37 * result + (int) this.getFileId();
         return result;
   }   


}


