package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * DeliverableFile generated by hbm2java
 */
@Entity
@Table(name="DeliverableFile", schema="dbo"
)
public class DeliverableFile  implements java.io.Serializable {


     private DeliverableFileId id;

    public DeliverableFile() {
    }

    public DeliverableFile(DeliverableFileId id) {
       this.id = id;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="deliverableId", column=@Column(name="DeliverableId", nullable=false, columnDefinition="bigint") ), 
        @AttributeOverride(name="fileId", column=@Column(name="FileId", nullable=false, columnDefinition="bigint") ) } )
    public DeliverableFileId getId() {
        return this.id;
    }
    
    public void setId(DeliverableFileId id) {
        this.id = id;
    }




}


