package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * DigitalEntitlement generated by hbm2java
 */
@Entity
@Table(name="DigitalEntitlement", schema="dbo"
    
)
public class DigitalEntitlement  implements java.io.Serializable {


     private Long entitlementId;
     private long orderItemId;
     private long customerId;
     private OffsetDateTime grantedAt;

    public DigitalEntitlement() {
    }

    public DigitalEntitlement(long orderItemId, long customerId, OffsetDateTime grantedAt) {
       this.orderItemId = orderItemId;
       this.customerId = customerId;
       this.grantedAt = grantedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EntitlementId", nullable=false, columnDefinition="bigint")
    public Long getEntitlementId() {
        return this.entitlementId;
    }
    
    public void setEntitlementId(Long entitlementId) {
        this.entitlementId = entitlementId;
    }

    
    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="CustomerId", nullable=false, columnDefinition="bigint")
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="GrantedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getGrantedAt() {
        return this.grantedAt;
    }
    
    public void setGrantedAt(OffsetDateTime grantedAt) {
        this.grantedAt = grantedAt;
    }




}


