package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * EntitlementAsset generated by hbm2java
 */
@Entity
@Table(name="EntitlementAsset", schema="dbo"
)
public class EntitlementAsset  implements java.io.Serializable {


     private EntitlementAssetId id;
     private long orderItemId;

    public EntitlementAsset() {
    }

    public EntitlementAsset(EntitlementAssetId id, long orderItemId) {
       this.id = id;
       this.orderItemId = orderItemId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="entitlementId", column=@Column(name="EntitlementId", nullable=false, columnDefinition="bigint") ), 
        @AttributeOverride(name="listingAssetId", column=@Column(name="ListingAssetId", nullable=false, columnDefinition="bigint") ) } )
    public EntitlementAssetId getId() {
        return this.id;
    }
    
    public void setId(EntitlementAssetId id) {
        this.id = id;
    }

    
    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(long orderItemId) {
        this.orderItemId = orderItemId;
    }




}


