package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * EntitlementAssetId generated by hbm2java
 */
@Embeddable
public class EntitlementAssetId  implements java.io.Serializable {


     private long entitlementId;
     private long listingAssetId;

    public EntitlementAssetId() {
    }

    public EntitlementAssetId(long entitlementId, long listingAssetId) {
       this.entitlementId = entitlementId;
       this.listingAssetId = listingAssetId;
    }
   


    @Column(name="EntitlementId", nullable=false, columnDefinition="bigint")
    public long getEntitlementId() {
        return this.entitlementId;
    }
    
    public void setEntitlementId(long entitlementId) {
        this.entitlementId = entitlementId;
    }


    @Column(name="ListingAssetId", nullable=false, columnDefinition="bigint")
    public long getListingAssetId() {
        return this.listingAssetId;
    }
    
    public void setListingAssetId(long listingAssetId) {
        this.listingAssetId = listingAssetId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EntitlementAssetId) ) return false;
		 EntitlementAssetId castOther = ( EntitlementAssetId ) other; 
         
		 return (this.getEntitlementId()==castOther.getEntitlementId())
 && (this.getListingAssetId()==castOther.getListingAssetId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + (int) this.getEntitlementId();
        result = 37 * result + (int) this.getListingAssetId();
         return result;
   }   


}


