package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * FulfillmentEvent generated by hbm2java
 */
@Entity
@Table(name="FulfillmentEvent", schema="dbo"
)
public class FulfillmentEvent  implements java.io.Serializable {


     private Long eventId;
     private long orderItemId;
     private String fromStatus;
     private String toStatus;
     private String reason;
     private OffsetDateTime occurredAt;
     private Long actorStaffId;

    public FulfillmentEvent() {
    }

	
    public FulfillmentEvent(long orderItemId, String toStatus, OffsetDateTime occurredAt) {
        this.orderItemId = orderItemId;
        this.toStatus = toStatus;
        this.occurredAt = occurredAt;
    }
    public FulfillmentEvent(long orderItemId, String fromStatus, String toStatus, String reason, OffsetDateTime occurredAt, Long actorStaffId) {
       this.orderItemId = orderItemId;
       this.fromStatus = fromStatus;
       this.toStatus = toStatus;
       this.reason = reason;
       this.occurredAt = occurredAt;
       this.actorStaffId = actorStaffId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="EventId", nullable=false, columnDefinition="bigint")
    public Long getEventId() {
        return this.eventId;
    }
    
    public void setEventId(Long eventId) {
        this.eventId = eventId;
    }

    
    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="FromStatus", length=20, columnDefinition="varchar(20)")
    public String getFromStatus() {
        return this.fromStatus;
    }
    
    public void setFromStatus(String fromStatus) {
        this.fromStatus = fromStatus;
    }

    
    @Column(name="ToStatus", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getToStatus() {
        return this.toStatus;
    }
    
    public void setToStatus(String toStatus) {
        this.toStatus = toStatus;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", length=1000, columnDefinition="nvarchar(1000)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="OccurredAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getOccurredAt() {
        return this.occurredAt;
    }
    
    public void setOccurredAt(OffsetDateTime occurredAt) {
        this.occurredAt = occurredAt;
    }

    
    @Column(name="ActorStaffId", columnDefinition="bigint")
    public Long getActorStaffId() {
        return this.actorStaffId;
    }
    
    public void setActorStaffId(Long actorStaffId) {
        this.actorStaffId = actorStaffId;
    }




}


