package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * Listing generated by hbm2java
 */
@Entity
@Table(name="Listing", schema="dbo"
    
)
public class Listing  implements java.io.Serializable {


     private Long listingId;
     private long artworkId;
     private String listingType;
     private String name;
     private String description;
     private String status;
     private String currencyCode;
     private BigDecimal price;
     private BigDecimal manufacturingCost;
     private BigDecimal artistMarkup;
     private String specifications;
     private boolean costReviewRequired;
     private OffsetDateTime createdAt;
     private OffsetDateTime publishedAt;
     private byte[] rowVer;

    public Listing() {
    }

	
    public Listing(long artworkId, String listingType, String name, String status, String currencyCode, BigDecimal price, boolean costReviewRequired, OffsetDateTime createdAt, byte[] rowVer) {
        this.artworkId = artworkId;
        this.listingType = listingType;
        this.name = name;
        this.status = status;
        this.currencyCode = currencyCode;
        this.price = price;
        this.costReviewRequired = costReviewRequired;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public Listing(long artworkId, String listingType, String name, String description, String status, String currencyCode, BigDecimal price, BigDecimal manufacturingCost, BigDecimal artistMarkup, String specifications, boolean costReviewRequired, OffsetDateTime createdAt, OffsetDateTime publishedAt, byte[] rowVer) {
       this.artworkId = artworkId;
       this.listingType = listingType;
       this.name = name;
       this.description = description;
       this.status = status;
       this.currencyCode = currencyCode;
       this.price = price;
       this.manufacturingCost = manufacturingCost;
       this.artistMarkup = artistMarkup;
       this.specifications = specifications;
       this.costReviewRequired = costReviewRequired;
       this.createdAt = createdAt;
       this.publishedAt = publishedAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ListingId", nullable=false, columnDefinition="bigint")
    public Long getListingId() {
        return this.listingId;
    }
    
    public void setListingId(Long listingId) {
        this.listingId = listingId;
    }

    
    @Column(name="ArtworkId", nullable=false, columnDefinition="bigint")
    public long getArtworkId() {
        return this.artworkId;
    }
    
    public void setArtworkId(long artworkId) {
        this.artworkId = artworkId;
    }

    
    @Column(name="ListingType", nullable=false, length=8, columnDefinition="varchar(8)")
    public String getListingType() {
        return this.listingType;
    }
    
    public void setListingType(String listingType) {
        this.listingType = listingType;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Name", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Description", length=2147483647, columnDefinition="nvarchar(max)")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="Price", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    
    @Column(name="ManufacturingCost", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getManufacturingCost() {
        return this.manufacturingCost;
    }
    
    public void setManufacturingCost(BigDecimal manufacturingCost) {
        this.manufacturingCost = manufacturingCost;
    }

    
    @Column(name="ArtistMarkup", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getArtistMarkup() {
        return this.artistMarkup;
    }
    
    public void setArtistMarkup(BigDecimal artistMarkup) {
        this.artistMarkup = artistMarkup;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Specifications", length=2147483647, columnDefinition="nvarchar(max)")
    public String getSpecifications() {
        return this.specifications;
    }
    
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    
    @Column(name="CostReviewRequired", nullable=false, columnDefinition="bit")
    public boolean isCostReviewRequired() {
        return this.costReviewRequired;
    }
    
    public void setCostReviewRequired(boolean costReviewRequired) {
        this.costReviewRequired = costReviewRequired;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PublishedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPublishedAt() {
        return this.publishedAt;
    }
    
    public void setPublishedAt(OffsetDateTime publishedAt) {
        this.publishedAt = publishedAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


