package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * ListingAsset generated by hbm2java
 */
@Entity
@Table(name="ListingAsset", schema="dbo"
    
)
public class ListingAsset  implements java.io.Serializable {


     private Long listingAssetId;
     private long listingId;
     private long fileId;
     private int sortOrder;
     private OffsetDateTime createdAt;

    public ListingAsset() {
    }

    public ListingAsset(long listingId, long fileId, int sortOrder, OffsetDateTime createdAt) {
       this.listingId = listingId;
       this.fileId = fileId;
       this.sortOrder = sortOrder;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ListingAssetId", nullable=false, columnDefinition="bigint")
    public Long getListingAssetId() {
        return this.listingAssetId;
    }
    
    public void setListingAssetId(Long listingAssetId) {
        this.listingAssetId = listingAssetId;
    }

    
    @Column(name="ListingId", nullable=false, columnDefinition="bigint")
    public long getListingId() {
        return this.listingId;
    }
    
    public void setListingId(long listingId) {
        this.listingId = listingId;
    }

    
    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }

    
    @Column(name="SortOrder", nullable=false, columnDefinition="int")
    public int getSortOrder() {
        return this.sortOrder;
    }
    
    public void setSortOrder(int sortOrder) {
        this.sortOrder = sortOrder;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


