package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * MarketplaceUser generated by hbm2java
 */
@Entity
@Table(name="MarketplaceUser", schema="dbo"
    
)
public class MarketplaceUser  implements java.io.Serializable {


     private Long userId;
     private String email;
     private String normalizedEmail;
     private byte[] passwordHash;
     private String displayName;
     private String status;
     private OffsetDateTime createdAt;
     private OffsetDateTime deletedAt;
     private byte[] rowVer;

    public MarketplaceUser() {
    }

	
    public MarketplaceUser(String status, OffsetDateTime createdAt, byte[] rowVer) {
        this.status = status;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public MarketplaceUser(String email, String normalizedEmail, byte[] passwordHash, String displayName, String status, OffsetDateTime createdAt, OffsetDateTime deletedAt, byte[] rowVer) {
       this.email = email;
       this.normalizedEmail = normalizedEmail;
       this.passwordHash = passwordHash;
       this.displayName = displayName;
       this.status = status;
       this.createdAt = createdAt;
       this.deletedAt = deletedAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="UserId", nullable=false, columnDefinition="bigint")
    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Email", length=320, columnDefinition="nvarchar(320)")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="NormalizedEmail", length=320, columnDefinition="nvarchar(320)")
    public String getNormalizedEmail() {
        return this.normalizedEmail;
    }
    
    public void setNormalizedEmail(String normalizedEmail) {
        this.normalizedEmail = normalizedEmail;
    }

    
    @Column(name="PasswordHash", length=512, columnDefinition="varbinary(512)")
    public byte[] getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(byte[] passwordHash) {
        this.passwordHash = passwordHash;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="DisplayName", length=160, columnDefinition="nvarchar(160)")
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="DeletedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getDeletedAt() {
        return this.deletedAt;
    }
    
    public void setDeletedAt(OffsetDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


