package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * MarketplaceOrder generated by hbm2java
 */
@Entity
@Table(name="MarketplaceOrder", schema="dbo"
)
public class MarketplaceOrder  implements java.io.Serializable {


     private Long orderId;
     private long customerId;
     private String status;
     private OffsetDateTime createdAt;
     private OffsetDateTime expiresAt;
     private OffsetDateTime paidAt;
     private String currencyCode;
     private BigDecimal itemsSubtotal;
     private BigDecimal shippingAmount;
     private BigDecimal taxAmount;
     private BigDecimal totalAmount;
     private String billingName;
     private String billingDetails;
     private String customerNameSnapshot;
     private String customerEmailSnapshot;
     private byte[] rowVer;

    public MarketplaceOrder() {
    }

	
    public MarketplaceOrder(long customerId, String status, OffsetDateTime createdAt, OffsetDateTime expiresAt, String currencyCode, BigDecimal itemsSubtotal, BigDecimal shippingAmount, BigDecimal taxAmount, byte[] rowVer) {
        this.customerId = customerId;
        this.status = status;
        this.createdAt = createdAt;
        this.expiresAt = expiresAt;
        this.currencyCode = currencyCode;
        this.itemsSubtotal = itemsSubtotal;
        this.shippingAmount = shippingAmount;
        this.taxAmount = taxAmount;
        this.rowVer = rowVer;
    }
    public MarketplaceOrder(long customerId, String status, OffsetDateTime createdAt, OffsetDateTime expiresAt, OffsetDateTime paidAt, String currencyCode, BigDecimal itemsSubtotal, BigDecimal shippingAmount, BigDecimal taxAmount, BigDecimal totalAmount, String billingName, String billingDetails, String customerNameSnapshot, String customerEmailSnapshot, byte[] rowVer) {
       this.customerId = customerId;
       this.status = status;
       this.createdAt = createdAt;
       this.expiresAt = expiresAt;
       this.paidAt = paidAt;
       this.currencyCode = currencyCode;
       this.itemsSubtotal = itemsSubtotal;
       this.shippingAmount = shippingAmount;
       this.taxAmount = taxAmount;
       this.totalAmount = totalAmount;
       this.billingName = billingName;
       this.billingDetails = billingDetails;
       this.customerNameSnapshot = customerNameSnapshot;
       this.customerEmailSnapshot = customerEmailSnapshot;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="OrderId", nullable=false, columnDefinition="bigint")
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="CustomerId", nullable=false, columnDefinition="bigint")
    public long getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    
    @Column(name="Status", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ExpiresAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getExpiresAt() {
        return this.expiresAt;
    }
    
    public void setExpiresAt(OffsetDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PaidAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPaidAt() {
        return this.paidAt;
    }
    
    public void setPaidAt(OffsetDateTime paidAt) {
        this.paidAt = paidAt;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="ItemsSubtotal", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getItemsSubtotal() {
        return this.itemsSubtotal;
    }
    
    public void setItemsSubtotal(BigDecimal itemsSubtotal) {
        this.itemsSubtotal = itemsSubtotal;
    }

    
    @Column(name="ShippingAmount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getShippingAmount() {
        return this.shippingAmount;
    }
    
    public void setShippingAmount(BigDecimal shippingAmount) {
        this.shippingAmount = shippingAmount;
    }

    
    @Column(name="TaxAmount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    
    @Column(name="TotalAmount", precision=21, scale=4, columnDefinition="decimal(21,4)")
    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="BillingName", length=160, columnDefinition="nvarchar(160)")
    public String getBillingName() {
        return this.billingName;
    }
    
    public void setBillingName(String billingName) {
        this.billingName = billingName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="BillingDetails", length=1000, columnDefinition="nvarchar(1000)")
    public String getBillingDetails() {
        return this.billingDetails;
    }
    
    public void setBillingDetails(String billingDetails) {
        this.billingDetails = billingDetails;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="CustomerNameSnapshot", length=160, columnDefinition="nvarchar(160)")
    public String getCustomerNameSnapshot() {
        return this.customerNameSnapshot;
    }
    
    public void setCustomerNameSnapshot(String customerNameSnapshot) {
        this.customerNameSnapshot = customerNameSnapshot;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="CustomerEmailSnapshot", length=320, columnDefinition="nvarchar(320)")
    public String getCustomerEmailSnapshot() {
        return this.customerEmailSnapshot;
    }
    
    public void setCustomerEmailSnapshot(String customerEmailSnapshot) {
        this.customerEmailSnapshot = customerEmailSnapshot;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


