package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * OrderShippingAddress generated by hbm2java
 */
@Entity
@Table(name="OrderShippingAddress", schema="dbo"
)
public class OrderShippingAddress  implements java.io.Serializable {


     private long orderId;
     private Long sourceAddressId;
     private String recipientName;
     private String phone;
     private String line1;
     private String line2;
     private String ward;
     private String district;
     private String provinceCode;
     private String provinceName;
     private String postalCode;
     private String countryCode;

    public OrderShippingAddress() {
    }

	
    public OrderShippingAddress(long orderId, String recipientName, String phone, String line1, String provinceCode, String provinceName, String countryCode) {
        this.orderId = orderId;
        this.recipientName = recipientName;
        this.phone = phone;
        this.line1 = line1;
        this.provinceCode = provinceCode;
        this.provinceName = provinceName;
        this.countryCode = countryCode;
    }
    public OrderShippingAddress(long orderId, Long sourceAddressId, String recipientName, String phone, String line1, String line2, String ward, String district, String provinceCode, String provinceName, String postalCode, String countryCode) {
       this.orderId = orderId;
       this.sourceAddressId = sourceAddressId;
       this.recipientName = recipientName;
       this.phone = phone;
       this.line1 = line1;
       this.line2 = line2;
       this.ward = ward;
       this.district = district;
       this.provinceCode = provinceCode;
       this.provinceName = provinceName;
       this.postalCode = postalCode;
       this.countryCode = countryCode;
    }
   
     @Id 

    
    @Column(name="OrderId", nullable=false, columnDefinition="bigint")
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="SourceAddressId", columnDefinition="bigint")
    public Long getSourceAddressId() {
        return this.sourceAddressId;
    }
    
    public void setSourceAddressId(Long sourceAddressId) {
        this.sourceAddressId = sourceAddressId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="RecipientName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getRecipientName() {
        return this.recipientName;
    }
    
    public void setRecipientName(String recipientName) {
        this.recipientName = recipientName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Phone", nullable=false, length=40, columnDefinition="nvarchar(40)")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Line1", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getLine1() {
        return this.line1;
    }
    
    public void setLine1(String line1) {
        this.line1 = line1;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Line2", length=240, columnDefinition="nvarchar(240)")
    public String getLine2() {
        return this.line2;
    }
    
    public void setLine2(String line2) {
        this.line2 = line2;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Ward", length=160, columnDefinition="nvarchar(160)")
    public String getWard() {
        return this.ward;
    }
    
    public void setWard(String ward) {
        this.ward = ward;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="District", length=160, columnDefinition="nvarchar(160)")
    public String getDistrict() {
        return this.district;
    }
    
    public void setDistrict(String district) {
        this.district = district;
    }

    
    @Column(name="ProvinceCode", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProvinceName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="PostalCode", length=20, columnDefinition="nvarchar(20)")
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="CountryCode", nullable=false, length=2, columnDefinition="char(2)")
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }




}


