package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;

/**
 * OrderItem generated by hbm2java
 */
@Entity
@Table(name="OrderItem", schema="dbo"
    
)
public class OrderItem  implements java.io.Serializable {


     private Long orderItemId;
     private long orderId;
     private long listingId;
     private String listingType;
     private long artworkId;
     private long artistId;
     private String artworkTitle;
     private String listingName;
     private String artistName;
     private String specifications;
     private int quantity;
     private String currencyCode;
     private BigDecimal unitPrice;
     private BigDecimal manufacturingCostPerUnit;
     private BigDecimal markupPerUnit;
     private BigDecimal feeRate;
     private BigDecimal feeAmount;
     private BigDecimal artistProceeds;
     private BigDecimal taxAmount;
     private BigDecimal lineSubtotal;

    public OrderItem() {
    }

	
    public OrderItem(long orderId, long listingId, String listingType, long artworkId, long artistId, String artworkTitle, String listingName, String artistName, int quantity, String currencyCode, BigDecimal unitPrice, BigDecimal feeRate, BigDecimal feeAmount, BigDecimal artistProceeds, BigDecimal taxAmount) {
        this.orderId = orderId;
        this.listingId = listingId;
        this.listingType = listingType;
        this.artworkId = artworkId;
        this.artistId = artistId;
        this.artworkTitle = artworkTitle;
        this.listingName = listingName;
        this.artistName = artistName;
        this.quantity = quantity;
        this.currencyCode = currencyCode;
        this.unitPrice = unitPrice;
        this.feeRate = feeRate;
        this.feeAmount = feeAmount;
        this.artistProceeds = artistProceeds;
        this.taxAmount = taxAmount;
    }
    public OrderItem(long orderId, long listingId, String listingType, long artworkId, long artistId, String artworkTitle, String listingName, String artistName, String specifications, int quantity, String currencyCode, BigDecimal unitPrice, BigDecimal manufacturingCostPerUnit, BigDecimal markupPerUnit, BigDecimal feeRate, BigDecimal feeAmount, BigDecimal artistProceeds, BigDecimal taxAmount, BigDecimal lineSubtotal) {
       this.orderId = orderId;
       this.listingId = listingId;
       this.listingType = listingType;
       this.artworkId = artworkId;
       this.artistId = artistId;
       this.artworkTitle = artworkTitle;
       this.listingName = listingName;
       this.artistName = artistName;
       this.specifications = specifications;
       this.quantity = quantity;
       this.currencyCode = currencyCode;
       this.unitPrice = unitPrice;
       this.manufacturingCostPerUnit = manufacturingCostPerUnit;
       this.markupPerUnit = markupPerUnit;
       this.feeRate = feeRate;
       this.feeAmount = feeAmount;
       this.artistProceeds = artistProceeds;
       this.taxAmount = taxAmount;
       this.lineSubtotal = lineSubtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public Long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="OrderId", nullable=false, columnDefinition="bigint")
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="ListingId", nullable=false, columnDefinition="bigint")
    public long getListingId() {
        return this.listingId;
    }
    
    public void setListingId(long listingId) {
        this.listingId = listingId;
    }

    
    @Column(name="ListingType", nullable=false, length=8, columnDefinition="varchar(8)")
    public String getListingType() {
        return this.listingType;
    }
    
    public void setListingType(String listingType) {
        this.listingType = listingType;
    }

    
    @Column(name="ArtworkId", nullable=false, columnDefinition="bigint")
    public long getArtworkId() {
        return this.artworkId;
    }
    
    public void setArtworkId(long artworkId) {
        this.artworkId = artworkId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ArtworkTitle", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getArtworkTitle() {
        return this.artworkTitle;
    }
    
    public void setArtworkTitle(String artworkTitle) {
        this.artworkTitle = artworkTitle;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ListingName", nullable=false, length=240, columnDefinition="nvarchar(240)")
    public String getListingName() {
        return this.listingName;
    }
    
    public void setListingName(String listingName) {
        this.listingName = listingName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ArtistName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getArtistName() {
        return this.artistName;
    }
    
    public void setArtistName(String artistName) {
        this.artistName = artistName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Specifications", length=2147483647, columnDefinition="nvarchar(max)")
    public String getSpecifications() {
        return this.specifications;
    }
    
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    
    @Column(name="Quantity", nullable=false, columnDefinition="int")
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="UnitPrice", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    
    @Column(name="ManufacturingCostPerUnit", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getManufacturingCostPerUnit() {
        return this.manufacturingCostPerUnit;
    }
    
    public void setManufacturingCostPerUnit(BigDecimal manufacturingCostPerUnit) {
        this.manufacturingCostPerUnit = manufacturingCostPerUnit;
    }

    
    @Column(name="MarkupPerUnit", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getMarkupPerUnit() {
        return this.markupPerUnit;
    }
    
    public void setMarkupPerUnit(BigDecimal markupPerUnit) {
        this.markupPerUnit = markupPerUnit;
    }

    
    @Column(name="FeeRate", nullable=false, precision=9, scale=6, columnDefinition="decimal(9,6)")
    public BigDecimal getFeeRate() {
        return this.feeRate;
    }
    
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    
    @Column(name="FeeAmount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getFeeAmount() {
        return this.feeAmount;
    }
    
    public void setFeeAmount(BigDecimal feeAmount) {
        this.feeAmount = feeAmount;
    }

    
    @Column(name="ArtistProceeds", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getArtistProceeds() {
        return this.artistProceeds;
    }
    
    public void setArtistProceeds(BigDecimal artistProceeds) {
        this.artistProceeds = artistProceeds;
    }

    
    @Column(name="TaxAmount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getTaxAmount() {
        return this.taxAmount;
    }
    
    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    
    @Column(name="LineSubtotal", precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getLineSubtotal() {
        return this.lineSubtotal;
    }
    
    public void setLineSubtotal(BigDecimal lineSubtotal) {
        this.lineSubtotal = lineSubtotal;
    }




}


