package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.AttributeOverride;
import jakarta.persistence.AttributeOverrides;
import jakarta.persistence.Column;
import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;

/**
 * OrderItemAsset generated by hbm2java
 */
@Entity
@Table(name="OrderItemAsset", schema="dbo"
)
public class OrderItemAsset  implements java.io.Serializable {


     private OrderItemAssetId id;
     private long listingId;
     private long fileId;

    public OrderItemAsset() {
    }

    public OrderItemAsset(OrderItemAssetId id, long listingId, long fileId) {
       this.id = id;
       this.listingId = listingId;
       this.fileId = fileId;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="listingAssetId", column=@Column(name="ListingAssetId", nullable=false, columnDefinition="bigint") ), 
        @AttributeOverride(name="orderItemId", column=@Column(name="OrderItemId", nullable=false, columnDefinition="bigint") ) } )
    public OrderItemAssetId getId() {
        return this.id;
    }
    
    public void setId(OrderItemAssetId id) {
        this.id = id;
    }

    
    @Column(name="ListingId", nullable=false, columnDefinition="bigint")
    public long getListingId() {
        return this.listingId;
    }
    
    public void setListingId(long listingId) {
        this.listingId = listingId;
    }

    
    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(long fileId) {
        this.fileId = fileId;
    }




}


