package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * OrderItemAssetId generated by hbm2java
 */
@Embeddable
public class OrderItemAssetId  implements java.io.Serializable {


     private long listingAssetId;
     private long orderItemId;

    public OrderItemAssetId() {
    }

    public OrderItemAssetId(long listingAssetId, long orderItemId) {
       this.listingAssetId = listingAssetId;
       this.orderItemId = orderItemId;
    }
   


    @Column(name="ListingAssetId", nullable=false, columnDefinition="bigint")
    public long getListingAssetId() {
        return this.listingAssetId;
    }
    
    public void setListingAssetId(long listingAssetId) {
        this.listingAssetId = listingAssetId;
    }


    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(long orderItemId) {
        this.orderItemId = orderItemId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OrderItemAssetId) ) return false;
		 OrderItemAssetId castOther = ( OrderItemAssetId ) other; 
         
		 return (this.getListingAssetId()==castOther.getListingAssetId())
 && (this.getOrderItemId()==castOther.getOrderItemId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + (int) this.getListingAssetId();
        result = 37 * result + (int) this.getOrderItemId();
         return result;
   }   


}


