package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * Payment generated by hbm2java
 */
@Entity
@Table(name="Payment", schema="dbo"
    
)
public class Payment  implements java.io.Serializable {


     private Long paymentId;
     private Long orderId;
     private Long quoteId;
     private BigDecimal amount;
     private String currencyCode;
     private String status;
     private OffsetDateTime succeededAt;
     private OffsetDateTime createdAt;
     private byte[] rowVer;

    public Payment() {
    }

	
    public Payment(BigDecimal amount, String currencyCode, String status, OffsetDateTime createdAt, byte[] rowVer) {
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.status = status;
        this.createdAt = createdAt;
        this.rowVer = rowVer;
    }
    public Payment(Long orderId, Long quoteId, BigDecimal amount, String currencyCode, String status, OffsetDateTime succeededAt, OffsetDateTime createdAt, byte[] rowVer) {
       this.orderId = orderId;
       this.quoteId = quoteId;
       this.amount = amount;
       this.currencyCode = currencyCode;
       this.status = status;
       this.succeededAt = succeededAt;
       this.createdAt = createdAt;
       this.rowVer = rowVer;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PaymentId", nullable=false, columnDefinition="bigint")
    public Long getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Long paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="OrderId", columnDefinition="bigint")
    public Long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="QuoteId", columnDefinition="bigint")
    public Long getQuoteId() {
        return this.quoteId;
    }
    
    public void setQuoteId(Long quoteId) {
        this.quoteId = quoteId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="SucceededAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getSucceededAt() {
        return this.succeededAt;
    }
    
    public void setSucceededAt(OffsetDateTime succeededAt) {
        this.succeededAt = succeededAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


