package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * PaymentAttempt generated by hbm2java
 */
@Entity
@Table(name="PaymentAttempt", schema="dbo"
    
)
public class PaymentAttempt  implements java.io.Serializable {


     private Long attemptId;
     private long paymentId;
     private String providerName;
     private String providerAttemptRef;
     private String providerTransactionRef;
     private String status;
     private OffsetDateTime createdAt;
     private OffsetDateTime confirmedAt;

    public PaymentAttempt() {
    }

	
    public PaymentAttempt(long paymentId, String providerName, String status, OffsetDateTime createdAt) {
        this.paymentId = paymentId;
        this.providerName = providerName;
        this.status = status;
        this.createdAt = createdAt;
    }
    public PaymentAttempt(long paymentId, String providerName, String providerAttemptRef, String providerTransactionRef, String status, OffsetDateTime createdAt, OffsetDateTime confirmedAt) {
       this.paymentId = paymentId;
       this.providerName = providerName;
       this.providerAttemptRef = providerAttemptRef;
       this.providerTransactionRef = providerTransactionRef;
       this.status = status;
       this.createdAt = createdAt;
       this.confirmedAt = confirmedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="AttemptId", nullable=false, columnDefinition="bigint")
    public Long getAttemptId() {
        return this.attemptId;
    }
    
    public void setAttemptId(Long attemptId) {
        this.attemptId = attemptId;
    }

    
    @Column(name="PaymentId", nullable=false, columnDefinition="bigint")
    public long getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(long paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="ProviderName", nullable=false, length=80, columnDefinition="varchar(80)")
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProviderAttemptRef", length=200, columnDefinition="nvarchar(200)")
    public String getProviderAttemptRef() {
        return this.providerAttemptRef;
    }
    
    public void setProviderAttemptRef(String providerAttemptRef) {
        this.providerAttemptRef = providerAttemptRef;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProviderTransactionRef", length=200, columnDefinition="nvarchar(200)")
    public String getProviderTransactionRef() {
        return this.providerTransactionRef;
    }
    
    public void setProviderTransactionRef(String providerTransactionRef) {
        this.providerTransactionRef = providerTransactionRef;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ConfirmedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getConfirmedAt() {
        return this.confirmedAt;
    }
    
    public void setConfirmedAt(OffsetDateTime confirmedAt) {
        this.confirmedAt = confirmedAt;
    }




}


