package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;

/**
 * PayoutLine generated by hbm2java
 */
@Entity
@Table(name="PayoutLine", schema="dbo"
    
)
public class PayoutLine  implements java.io.Serializable {


     private Long payoutLineId;
     private long payoutId;
     private long proceedsId;
     private BigDecimal amount;
     private boolean isActive;

    public PayoutLine() {
    }

    public PayoutLine(long payoutId, long proceedsId, BigDecimal amount, boolean isActive) {
       this.payoutId = payoutId;
       this.proceedsId = proceedsId;
       this.amount = amount;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PayoutLineId", nullable=false, columnDefinition="bigint")
    public Long getPayoutLineId() {
        return this.payoutLineId;
    }
    
    public void setPayoutLineId(Long payoutLineId) {
        this.payoutLineId = payoutLineId;
    }

    
    @Column(name="PayoutId", nullable=false, columnDefinition="bigint")
    public long getPayoutId() {
        return this.payoutId;
    }
    
    public void setPayoutId(long payoutId) {
        this.payoutId = payoutId;
    }

    
    @Column(name="ProceedsId", nullable=false, columnDefinition="bigint")
    public long getProceedsId() {
        return this.proceedsId;
    }
    
    public void setProceedsId(long proceedsId) {
        this.proceedsId = proceedsId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="IsActive", nullable=false, columnDefinition="bit")
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


