package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * Payout generated by hbm2java
 */
@Entity
@Table(name="Payout", schema="dbo"
    
)
public class Payout  implements java.io.Serializable {


     private Long payoutId;
     private long artistId;
     private BigDecimal amount;
     private String currencyCode;
     private String status;
     private String providerName;
     private String providerPayoutRef;
     private OffsetDateTime createdAt;
     private OffsetDateTime paidAt;

    public Payout() {
    }

	
    public Payout(long artistId, BigDecimal amount, String currencyCode, String status, OffsetDateTime createdAt) {
        this.artistId = artistId;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.status = status;
        this.createdAt = createdAt;
    }
    public Payout(long artistId, BigDecimal amount, String currencyCode, String status, String providerName, String providerPayoutRef, OffsetDateTime createdAt, OffsetDateTime paidAt) {
       this.artistId = artistId;
       this.amount = amount;
       this.currencyCode = currencyCode;
       this.status = status;
       this.providerName = providerName;
       this.providerPayoutRef = providerPayoutRef;
       this.createdAt = createdAt;
       this.paidAt = paidAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="PayoutId", nullable=false, columnDefinition="bigint")
    public Long getPayoutId() {
        return this.payoutId;
    }
    
    public void setPayoutId(Long payoutId) {
        this.payoutId = payoutId;
    }

    
    @Column(name="ArtistId", nullable=false, columnDefinition="bigint")
    public long getArtistId() {
        return this.artistId;
    }
    
    public void setArtistId(long artistId) {
        this.artistId = artistId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="ProviderName", length=80, columnDefinition="varchar(80)")
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProviderPayoutRef", length=200, columnDefinition="nvarchar(200)")
    public String getProviderPayoutRef() {
        return this.providerPayoutRef;
    }
    
    public void setProviderPayoutRef(String providerPayoutRef) {
        this.providerPayoutRef = providerPayoutRef;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="PaidAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getPaidAt() {
        return this.paidAt;
    }
    
    public void setPaidAt(OffsetDateTime paidAt) {
        this.paidAt = paidAt;
    }




}


