package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * PhysicalFulfillment generated by hbm2java
 */
@Entity
@Table(name="PhysicalFulfillment", schema="dbo"
)
public class PhysicalFulfillment  implements java.io.Serializable {


     private long orderItemId;
     private String listingType;
     private String status;
     private String carrier;
     private String trackingReference;
     private OffsetDateTime deliveredAt;
     private OffsetDateTime updatedAt;
     private byte[] rowVer;

    public PhysicalFulfillment() {
    }

	
    public PhysicalFulfillment(long orderItemId, String listingType, String status, OffsetDateTime updatedAt, byte[] rowVer) {
        this.orderItemId = orderItemId;
        this.listingType = listingType;
        this.status = status;
        this.updatedAt = updatedAt;
        this.rowVer = rowVer;
    }
    public PhysicalFulfillment(long orderItemId, String listingType, String status, String carrier, String trackingReference, OffsetDateTime deliveredAt, OffsetDateTime updatedAt, byte[] rowVer) {
       this.orderItemId = orderItemId;
       this.listingType = listingType;
       this.status = status;
       this.carrier = carrier;
       this.trackingReference = trackingReference;
       this.deliveredAt = deliveredAt;
       this.updatedAt = updatedAt;
       this.rowVer = rowVer;
    }
   
     @Id 

    
    @Column(name="OrderItemId", nullable=false, columnDefinition="bigint")
    public long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="ListingType", nullable=false, length=8, columnDefinition="varchar(8)")
    public String getListingType() {
        return this.listingType;
    }
    
    public void setListingType(String listingType) {
        this.listingType = listingType;
    }

    
    @Column(name="Status", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Carrier", length=120, columnDefinition="nvarchar(120)")
    public String getCarrier() {
        return this.carrier;
    }
    
    public void setCarrier(String carrier) {
        this.carrier = carrier;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="TrackingReference", length=160, columnDefinition="nvarchar(160)")
    public String getTrackingReference() {
        return this.trackingReference;
    }
    
    public void setTrackingReference(String trackingReference) {
        this.trackingReference = trackingReference;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="DeliveredAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getDeliveredAt() {
        return this.deliveredAt;
    }
    
    public void setDeliveredAt(OffsetDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="UpdatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    
    @jakarta.persistence.Version
    @org.hibernate.annotations.Generated(event={org.hibernate.generator.EventType.INSERT, org.hibernate.generator.EventType.UPDATE})
    @Column(name="RowVer", nullable=false, insertable=false, updatable=false, columnDefinition="timestamp")
    public byte[] getRowVer() {
        return this.rowVer;
    }
    
    public void setRowVer(byte[] rowVer) {
        this.rowVer = rowVer;
    }




}


