package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * PlatformFeeRate generated by hbm2java
 */
@Entity
@Table(name="PlatformFeeRate", schema="dbo"
    
)
public class PlatformFeeRate  implements java.io.Serializable {


     private Long feeRateId;
     private OffsetDateTime effectiveFrom;
     private BigDecimal rate;
     private long setByStaffId;
     private OffsetDateTime createdAt;

    public PlatformFeeRate() {
    }

    public PlatformFeeRate(OffsetDateTime effectiveFrom, BigDecimal rate, long setByStaffId, OffsetDateTime createdAt) {
       this.effectiveFrom = effectiveFrom;
       this.rate = rate;
       this.setByStaffId = setByStaffId;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FeeRateId", nullable=false, columnDefinition="bigint")
    public Long getFeeRateId() {
        return this.feeRateId;
    }
    
    public void setFeeRateId(Long feeRateId) {
        this.feeRateId = feeRateId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="EffectiveFrom", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getEffectiveFrom() {
        return this.effectiveFrom;
    }
    
    public void setEffectiveFrom(OffsetDateTime effectiveFrom) {
        this.effectiveFrom = effectiveFrom;
    }

    
    @Column(name="Rate", nullable=false, precision=9, scale=6, columnDefinition="decimal(9,6)")
    public BigDecimal getRate() {
        return this.rate;
    }
    
    public void setRate(BigDecimal rate) {
        this.rate = rate;
    }

    
    @Column(name="SetByStaffId", nullable=false, columnDefinition="bigint")
    public long getSetByStaffId() {
        return this.setByStaffId;
    }
    
    public void setSetByStaffId(long setByStaffId) {
        this.setByStaffId = setByStaffId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


