package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * ProviderEvent generated by hbm2java
 */
@Entity
@Table(name="ProviderEvent", schema="dbo"
    
)
public class ProviderEvent  implements java.io.Serializable {


     private Long providerEventId;
     private String providerName;
     private String externalEventId;
     private Long attemptId;
     private OffsetDateTime receivedAt;
     private OffsetDateTime processedAt;
     private String outcome;

    public ProviderEvent() {
    }

	
    public ProviderEvent(String providerName, String externalEventId, OffsetDateTime receivedAt, String outcome) {
        this.providerName = providerName;
        this.externalEventId = externalEventId;
        this.receivedAt = receivedAt;
        this.outcome = outcome;
    }
    public ProviderEvent(String providerName, String externalEventId, Long attemptId, OffsetDateTime receivedAt, OffsetDateTime processedAt, String outcome) {
       this.providerName = providerName;
       this.externalEventId = externalEventId;
       this.attemptId = attemptId;
       this.receivedAt = receivedAt;
       this.processedAt = processedAt;
       this.outcome = outcome;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ProviderEventId", nullable=false, columnDefinition="bigint")
    public Long getProviderEventId() {
        return this.providerEventId;
    }
    
    public void setProviderEventId(Long providerEventId) {
        this.providerEventId = providerEventId;
    }

    
    @Column(name="ProviderName", nullable=false, length=80, columnDefinition="varchar(80)")
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ExternalEventId", nullable=false, length=200, columnDefinition="nvarchar(200)")
    public String getExternalEventId() {
        return this.externalEventId;
    }
    
    public void setExternalEventId(String externalEventId) {
        this.externalEventId = externalEventId;
    }

    
    @Column(name="AttemptId", columnDefinition="bigint")
    public Long getAttemptId() {
        return this.attemptId;
    }
    
    public void setAttemptId(Long attemptId) {
        this.attemptId = attemptId;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ReceivedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getReceivedAt() {
        return this.receivedAt;
    }
    
    public void setReceivedAt(OffsetDateTime receivedAt) {
        this.receivedAt = receivedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="ProcessedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getProcessedAt() {
        return this.processedAt;
    }
    
    public void setProcessedAt(OffsetDateTime processedAt) {
        this.processedAt = processedAt;
    }

    
    @Column(name="Outcome", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getOutcome() {
        return this.outcome;
    }
    
    public void setOutcome(String outcome) {
        this.outcome = outcome;
    }




}


