package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * RefundRequest generated by hbm2java
 */
@Entity
@Table(name="RefundRequest", schema="dbo"
    
)
public class RefundRequest  implements java.io.Serializable {


     private Long refundRequestId;
     private Long orderItemId;
     private Long commissionId;
     private long requestedByUserId;
     private String reason;
     private String status;
     private OffsetDateTime requestedAt;
     private OffsetDateTime decidedAt;
     private Long decidedByStaffId;
     private String decisionReason;

    public RefundRequest() {
    }

	
    public RefundRequest(long requestedByUserId, String reason, String status, OffsetDateTime requestedAt) {
        this.requestedByUserId = requestedByUserId;
        this.reason = reason;
        this.status = status;
        this.requestedAt = requestedAt;
    }
    public RefundRequest(Long orderItemId, Long commissionId, long requestedByUserId, String reason, String status, OffsetDateTime requestedAt, OffsetDateTime decidedAt, Long decidedByStaffId, String decisionReason) {
       this.orderItemId = orderItemId;
       this.commissionId = commissionId;
       this.requestedByUserId = requestedByUserId;
       this.reason = reason;
       this.status = status;
       this.requestedAt = requestedAt;
       this.decidedAt = decidedAt;
       this.decidedByStaffId = decidedByStaffId;
       this.decisionReason = decisionReason;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RefundRequestId", nullable=false, columnDefinition="bigint")
    public Long getRefundRequestId() {
        return this.refundRequestId;
    }
    
    public void setRefundRequestId(Long refundRequestId) {
        this.refundRequestId = refundRequestId;
    }

    
    @Column(name="OrderItemId", columnDefinition="bigint")
    public Long getOrderItemId() {
        return this.orderItemId;
    }
    
    public void setOrderItemId(Long orderItemId) {
        this.orderItemId = orderItemId;
    }

    
    @Column(name="CommissionId", columnDefinition="bigint")
    public Long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(Long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="RequestedByUserId", nullable=false, columnDefinition="bigint")
    public long getRequestedByUserId() {
        return this.requestedByUserId;
    }
    
    public void setRequestedByUserId(long requestedByUserId) {
        this.requestedByUserId = requestedByUserId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Reason", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getReason() {
        return this.reason;
    }
    
    public void setReason(String reason) {
        this.reason = reason;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="RequestedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getRequestedAt() {
        return this.requestedAt;
    }
    
    public void setRequestedAt(OffsetDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="DecidedAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getDecidedAt() {
        return this.decidedAt;
    }
    
    public void setDecidedAt(OffsetDateTime decidedAt) {
        this.decidedAt = decidedAt;
    }

    
    @Column(name="DecidedByStaffId", columnDefinition="bigint")
    public Long getDecidedByStaffId() {
        return this.decidedByStaffId;
    }
    
    public void setDecidedByStaffId(Long decidedByStaffId) {
        this.decidedByStaffId = decidedByStaffId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="DecisionReason", length=2000, columnDefinition="nvarchar(2000)")
    public String getDecisionReason() {
        return this.decisionReason;
    }
    
    public void setDecisionReason(String decisionReason) {
        this.decisionReason = decisionReason;
    }




}


