package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * RefundTransfer generated by hbm2java
 */
@Entity
@Table(name="RefundTransfer", schema="dbo"
    
)
public class RefundTransfer  implements java.io.Serializable {


     private Long refundTransferId;
     private long refundRequestId;
     private long paymentId;
     private BigDecimal amount;
     private String currencyCode;
     private String providerName;
     private String providerRefundRef;
     private String status;
     private OffsetDateTime createdAt;
     private OffsetDateTime succeededAt;

    public RefundTransfer() {
    }

	
    public RefundTransfer(long refundRequestId, long paymentId, BigDecimal amount, String currencyCode, String status, OffsetDateTime createdAt) {
        this.refundRequestId = refundRequestId;
        this.paymentId = paymentId;
        this.amount = amount;
        this.currencyCode = currencyCode;
        this.status = status;
        this.createdAt = createdAt;
    }
    public RefundTransfer(long refundRequestId, long paymentId, BigDecimal amount, String currencyCode, String providerName, String providerRefundRef, String status, OffsetDateTime createdAt, OffsetDateTime succeededAt) {
       this.refundRequestId = refundRequestId;
       this.paymentId = paymentId;
       this.amount = amount;
       this.currencyCode = currencyCode;
       this.providerName = providerName;
       this.providerRefundRef = providerRefundRef;
       this.status = status;
       this.createdAt = createdAt;
       this.succeededAt = succeededAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RefundTransferId", nullable=false, columnDefinition="bigint")
    public Long getRefundTransferId() {
        return this.refundTransferId;
    }
    
    public void setRefundTransferId(Long refundTransferId) {
        this.refundTransferId = refundTransferId;
    }

    
    @Column(name="RefundRequestId", nullable=false, columnDefinition="bigint")
    public long getRefundRequestId() {
        return this.refundRequestId;
    }
    
    public void setRefundRequestId(long refundRequestId) {
        this.refundRequestId = refundRequestId;
    }

    
    @Column(name="PaymentId", nullable=false, columnDefinition="bigint")
    public long getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(long paymentId) {
        this.paymentId = paymentId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @Column(name="CurrencyCode", nullable=false, length=3, columnDefinition="char(3)")
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="ProviderName", length=80, columnDefinition="varchar(80)")
    public String getProviderName() {
        return this.providerName;
    }
    
    public void setProviderName(String providerName) {
        this.providerName = providerName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProviderRefundRef", length=200, columnDefinition="nvarchar(200)")
    public String getProviderRefundRef() {
        return this.providerRefundRef;
    }
    
    public void setProviderRefundRef(String providerRefundRef) {
        this.providerRefundRef = providerRefundRef;
    }

    
    @Column(name="Status", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="SucceededAt", columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getSucceededAt() {
        return this.succeededAt;
    }
    
    public void setSucceededAt(OffsetDateTime succeededAt) {
        this.succeededAt = succeededAt;
    }




}


