package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * RevisionRequest generated by hbm2java
 */
@Entity
@Table(name="RevisionRequest", schema="dbo"
)
public class RevisionRequest  implements java.io.Serializable {


     private Long revisionId;
     private long deliverableId;
     private long commissionId;
     private long requestedByUserId;
     private String details;
     private OffsetDateTime requestedAt;

    public RevisionRequest() {
    }

    public RevisionRequest(long deliverableId, long commissionId, long requestedByUserId, String details, OffsetDateTime requestedAt) {
       this.deliverableId = deliverableId;
       this.commissionId = commissionId;
       this.requestedByUserId = requestedByUserId;
       this.details = details;
       this.requestedAt = requestedAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="RevisionId", nullable=false, columnDefinition="bigint")
    public Long getRevisionId() {
        return this.revisionId;
    }
    
    public void setRevisionId(Long revisionId) {
        this.revisionId = revisionId;
    }

    
    @Column(name="DeliverableId", nullable=false, columnDefinition="bigint")
    public long getDeliverableId() {
        return this.deliverableId;
    }
    
    public void setDeliverableId(long deliverableId) {
        this.deliverableId = deliverableId;
    }

    
    @Column(name="CommissionId", nullable=false, columnDefinition="bigint")
    public long getCommissionId() {
        return this.commissionId;
    }
    
    public void setCommissionId(long commissionId) {
        this.commissionId = commissionId;
    }

    
    @Column(name="RequestedByUserId", nullable=false, columnDefinition="bigint")
    public long getRequestedByUserId() {
        return this.requestedByUserId;
    }
    
    public void setRequestedByUserId(long requestedByUserId) {
        this.requestedByUserId = requestedByUserId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Details", nullable=false, length=2147483647, columnDefinition="nvarchar(max)")
    public String getDetails() {
        return this.details;
    }
    
    public void setDetails(String details) {
        this.details = details;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="RequestedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getRequestedAt() {
        return this.requestedAt;
    }
    
    public void setRequestedAt(OffsetDateTime requestedAt) {
        this.requestedAt = requestedAt;
    }




}


