package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * ShippingRefund generated by hbm2java
 */
@Entity
@Table(name="ShippingRefund", schema="dbo"
    
)
public class ShippingRefund  implements java.io.Serializable {


     private long orderId;
     private long refundRequestId;
     private BigDecimal amount;
     private OffsetDateTime createdAt;

    public ShippingRefund() {
    }

    public ShippingRefund(long orderId, long refundRequestId, BigDecimal amount, OffsetDateTime createdAt) {
       this.orderId = orderId;
       this.refundRequestId = refundRequestId;
       this.amount = amount;
       this.createdAt = createdAt;
    }
   
     @Id 

    
    @Column(name="OrderId", nullable=false, columnDefinition="bigint")
    public long getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(long orderId) {
        this.orderId = orderId;
    }

    
    @Column(name="RefundRequestId", nullable=false, columnDefinition="bigint")
    public long getRefundRequestId() {
        return this.refundRequestId;
    }
    
    public void setRefundRequestId(long refundRequestId) {
        this.refundRequestId = refundRequestId;
    }

    
    @Column(name="Amount", nullable=false, precision=19, scale=4, columnDefinition="decimal(19,4)")
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


