package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * StaffAccount generated by hbm2java
 */
@Entity
@Table(name="StaffAccount", schema="dbo"
    
)
public class StaffAccount  implements java.io.Serializable {


     private Long staffId;
     private String loginName;
     private byte[] passwordHash;
     private String role;
     private boolean isActive;
     private OffsetDateTime createdAt;

    public StaffAccount() {
    }

    public StaffAccount(String loginName, byte[] passwordHash, String role, boolean isActive, OffsetDateTime createdAt) {
       this.loginName = loginName;
       this.passwordHash = passwordHash;
       this.role = role;
       this.isActive = isActive;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="StaffId", nullable=false, columnDefinition="bigint")
    public Long getStaffId() {
        return this.staffId;
    }
    
    public void setStaffId(Long staffId) {
        this.staffId = staffId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="LoginName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    
    @Column(name="PasswordHash", nullable=false, length=512, columnDefinition="varbinary(512)")
    public byte[] getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(byte[] passwordHash) {
        this.passwordHash = passwordHash;
    }

    
    @Column(name="Role", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="IsActive", nullable=false, columnDefinition="bit")
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


