package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * StoredFile generated by hbm2java
 */
@Entity
@Table(name="StoredFile", schema="dbo"
    
)
public class StoredFile  implements java.io.Serializable {


     private Long fileId;
     private String storageKey;
     private String originalName;
     private String contentType;
     private long byteLength;
     private byte[] sha256;
     private String accessClass;
     private OffsetDateTime createdAt;

    public StoredFile() {
    }

	
    public StoredFile(String storageKey, String originalName, String contentType, long byteLength, String accessClass, OffsetDateTime createdAt) {
        this.storageKey = storageKey;
        this.originalName = originalName;
        this.contentType = contentType;
        this.byteLength = byteLength;
        this.accessClass = accessClass;
        this.createdAt = createdAt;
    }
    public StoredFile(String storageKey, String originalName, String contentType, long byteLength, byte[] sha256, String accessClass, OffsetDateTime createdAt) {
       this.storageKey = storageKey;
       this.originalName = originalName;
       this.contentType = contentType;
       this.byteLength = byteLength;
       this.sha256 = sha256;
       this.accessClass = accessClass;
       this.createdAt = createdAt;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="FileId", nullable=false, columnDefinition="bigint")
    public Long getFileId() {
        return this.fileId;
    }
    
    public void setFileId(Long fileId) {
        this.fileId = fileId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="StorageKey", nullable=false, length=500, columnDefinition="nvarchar(500)")
    public String getStorageKey() {
        return this.storageKey;
    }
    
    public void setStorageKey(String storageKey) {
        this.storageKey = storageKey;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="OriginalName", nullable=false, length=260, columnDefinition="nvarchar(260)")
    public String getOriginalName() {
        return this.originalName;
    }
    
    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ContentType", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getContentType() {
        return this.contentType;
    }
    
    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    
    @Column(name="ByteLength", nullable=false, columnDefinition="bigint")
    public long getByteLength() {
        return this.byteLength;
    }
    
    public void setByteLength(long byteLength) {
        this.byteLength = byteLength;
    }

    
    @Column(name="Sha256", length=32, columnDefinition="binary(32)")
    public byte[] getSha256() {
        return this.sha256;
    }
    
    public void setSha256(byte[] sha256) {
        this.sha256 = sha256;
    }

    
    @Column(name="AccessClass", nullable=false, length=16, columnDefinition="varchar(16)")
    public String getAccessClass() {
        return this.accessClass;
    }
    
    public void setAccessClass(String accessClass) {
        this.accessClass = accessClass;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="CreatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }




}


