package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.OffsetDateTime;

/**
 * SupportedProvince generated by hbm2java
 */
@Entity
@Table(name="SupportedProvince", schema="dbo"
)
public class SupportedProvince  implements java.io.Serializable {


     private String provinceCode;
     private String provinceName;
     private boolean isSupported;
     private OffsetDateTime updatedAt;

    public SupportedProvince() {
    }

    public SupportedProvince(String provinceCode, String provinceName, boolean isSupported, OffsetDateTime updatedAt) {
       this.provinceCode = provinceCode;
       this.provinceName = provinceName;
       this.isSupported = isSupported;
       this.updatedAt = updatedAt;
    }
   
     @Id 

    
    @Column(name="ProvinceCode", nullable=false, length=20, columnDefinition="varchar(20)")
    public String getProvinceCode() {
        return this.provinceCode;
    }
    
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="ProvinceName", nullable=false, length=160, columnDefinition="nvarchar(160)")
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    
    @Column(name="IsSupported", nullable=false, columnDefinition="bit")
    public boolean isIsSupported() {
        return this.isSupported;
    }
    
    public void setIsSupported(boolean isSupported) {
        this.isSupported = isSupported;
    }

    
    @org.hibernate.annotations.TimeZoneStorage(org.hibernate.annotations.TimeZoneStorageType.NATIVE)
    @Column(name="UpdatedAt", nullable=false, columnDefinition="datetimeoffset(0)")
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }




}


