package com.exe101.entity;
// Generated by Hibernate Tools 7.3.13.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="Tag", schema="dbo"
    
)
public class Tag  implements java.io.Serializable {


     private Integer tagId;
     private String name;
     private boolean isActive;

    public Tag() {
    }

    public Tag(String name, boolean isActive) {
       this.name = name;
       this.isActive = isActive;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="TagId", nullable=false, columnDefinition="int")
    public Integer getTagId() {
        return this.tagId;
    }
    
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    
    @org.hibernate.annotations.Nationalized
    @Column(name="Name", nullable=false, length=100, columnDefinition="nvarchar(100)")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="IsActive", nullable=false, columnDefinition="bit")
    public boolean isIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }




}


